### ISSUE TITLE
Creating log profile with storage account transient error

### ISSUE THREAD

**Issue by Michael-Coetzee** [microsoft/AzureMonitorCommunity#96]
AZ_VERSION
```
{
  "azure-cli": "2.32.0",
  "azure-cli-core": "2.32.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "log-analytics": "0.2.2",
    "log-analytics-solution": "0.1.1"
  }
}
```

Linking log profiles to storage account, tried through various methods. Results in the same error message. 
`"code":"StorageAccountNotAccessible"` 

```
STORAGEACCOUNT_ID=$(az storage account show --resource-group <rg-name> --name <storage-account>  --query id -o tsv)
az monitor log-profiles create \                                                                                                                                    6s 
  --name <log-profile-name> --categories "Delete" "Write" "Action" --days 30 --enabled true \
  --storage-account-id $STORAGEACCOUNT_ID --location $LOCATION --locations $LOCATIONS 
```
ERROR:
```
cli.azure.cli.core.sdk.policies: {"code":"StorageAccountNotAccessible","message":"There is a transient issue accessing the provided storage account. Please try again."}
cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
cli.azure.cli.core.util: Traceback (most recent call last):
  File "/opt/azure-cli/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/azure-cli/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/opt/azure-cli/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/azure-cli/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 713, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/opt/azure-cli/lib/python3.10/site-packages/azure/cli/command_modules/monitor/_exception_handler.py", line 23, in exception_handler
    raise ex
  File "/opt/azure-cli/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/opt/azure-cli/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/azure-cli/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/azure-cli/lib/python3.10/site-packages/azure/cli/command_modules/monitor/operations/log_profiles.py", line 14, in create_log_profile_operations
    return client.create_or_update(log_profile_name=name, parameters=parameters)
  File "/opt/azure-cli/lib/python3.10/site-packages/azure/mgmt/monitor/v2016_03_01/operations/_log_profiles_operations.py", line 206, in create_or_update
    map_error(status_code=response.status_code, response=response, error_map=error_map)
  File "/opt/azure-cli/lib/python3.10/site-packages/azure/core/exceptions.py", line 105, in map_error
    raise error
azure.core.exceptions.ResourceExistsError: (StorageAccountNotAccessible) There is a transient issue accessing the provided storage account. Please try again.
Code: StorageAccountNotAccessible
Message: There is a transient issue accessing the provided storage account. Please try again.

cli.azure.cli.core.azclierror: (StorageAccountNotAccessible) There is a transient issue accessing the provided storage account. Please try again.
Code: StorageAccountNotAccessible
Message: There is a transient issue accessing the provided storage account. Please try again.
az_command_data_logger: (StorageAccountNotAccessible) There is a transient issue accessing the provided storage account. Please try again.
Code: StorageAccountNotAccessible
Message: There is a transient issue accessing the provided storage account. Please try again.
```
Also tried through rest 

```
az rest -m PUT --uri "https://management.azure.com/subscriptions/<sub-id>/providers/Microsoft.Insights/logprofiles/<profile-name>?api-version=2016-03-01" --body '{"location":"<location>","properties":{"locations":["global","<location>"],"categories":["Write","Delete","Action"],"retentionPolicy":{"enabled":true,"days":3},"storageAccountId":"<storage-account-resource-id>"}}' --headers "Content-Type=application/json"
```
Results are all the same. 
Tried with different SKU's deleting and recreating the storage account, different service principals, my account which is Contributor, always results in the same error.  

Your help would be appreciated.

**Comment by Michael-Coetzee** [comment]
Looks like this might be the wrong wrong channel, re-posted on azure cli
